"""Venom IR utilities for pydefi.

This module provides :class:`ModuleBuilder` — a :class:`~vyper.venom.builder.VenomBuilder`
subclass that auto-prefixes all generated labels under a namespace, enabling multiple
independently-generated code+data blocks to be merged into one :class:`~vyper.venom.context.IRContext`
without label collisions.

Calling convention for internal functions
-----------------------------------------

When building functions callable via ``invoke``, the last ``param()`` is always
the **return PC** (the address to jump back to after the function completes).
Correspondingly, ``ret()`` must receive the return values first and the return PC
**last**:

.. code-block:: python

    fn = mod.create_function("add")
    mod.set_block(fn.entry)
    x          = mod.param()          # first argument
    y          = mod.param()          # second argument
    return_pc  = mod.param()          # return-PC is always the last param
    result     = mod.add(x, y)
    mod.ret(result, return_pc)        # value(s), then return_pc

    # Caller side:
    rets = main.invoke(IRLabel("mod_add"), [IRLiteral(3), IRLiteral(4)], returns=1)

Data sections
-------------

Use :meth:`append_data_section` / :meth:`append_data_item` to attach constant
byte data.  To read it at runtime, combine :meth:`~vyper.venom.builder.VenomBuilder.offset`
with :meth:`~vyper.venom.builder.VenomBuilder.codecopy` — **do not** use
:meth:`~vyper.venom.builder.VenomBuilder.dload` (which adds ``code_end``, the total
bytecode length, instead of the code-section end):

.. code-block:: python

    mod.append_data_section("table")
    mod.append_data_item(b"\\x00" * 31 + b"\\x2a")   # literal 42

    src  = mod.offset(IRLiteral(0), mod.named_label("table"))
    buf  = mod.alloca(32)
    mod.codecopy(buf, src, IRLiteral(32))
    val  = mod.mload(buf)

Typical usage::

    from pydefi.vm.venom import ModuleBuilder
    from vyper.venom.basicblock import IRLabel, IRLiteral

    # Build module A
    mod_a = ModuleBuilder("mod_a")
    mod_a.append_data_section("table")               # DataSection(IRLabel("mod_a_table"))
    mod_a.append_data_item(b"\\x01\\x02\\x03\\x04")

    addr = mod_a.offset(IRLiteral(0), mod_a.named_label("table"))
    buf  = mod_a.alloca(32)
    mod_a.codecopy(buf, addr, IRLiteral(4))
    mod_a.stop()

    # Build module B — cross-module reference to A's table
    mod_b = ModuleBuilder("mod_b")
    addr_a = mod_b.offset(IRLiteral(0), IRLabel("mod_a_table"))
    buf2   = mod_b.alloca(32)
    mod_b.codecopy(buf2, addr_a, IRLiteral(4))
    mod_b.stop()

    # Merge everything and compile
    main = ModuleBuilder("main")
    main.merge(mod_a.ctx, mod_b.ctx)
    bytecode = main.compile()
"""

from __future__ import annotations

from vyper.compiler.settings import VenomOptimizationFlags
from vyper.evm.assembler.core import assembly_to_evm
from vyper.venom import VenomCompiler, run_passes_on
from vyper.venom.basicblock import IRBasicBlock, IRLabel
from vyper.venom.builder import VenomBuilder
from vyper.venom.context import DataSection, IRContext
from vyper.venom.function import IRFunction

__all__ = ["ModuleBuilder"]


def _clone_function(fn: IRFunction) -> IRFunction:
    """Clone *fn* into a fresh :class:`~vyper.venom.function.IRFunction`.

    Workarounds applied:

    * upstream ``IRFunction.copy()`` double-appends the auto-created entry
      block — we clear it first;
    * upstream ``IRBasicBlock.copy()`` keeps the original ``parent`` reference —
      we reparent each cloned block to the new function.
    """
    new = IRFunction(fn.name)
    new.clear_basic_blocks()
    for bb in fn.get_basic_blocks():
        new_bb = bb.copy()
        new_bb.parent = new
        new.append_basic_block(new_bb)
    new.last_variable = fn.last_variable
    return new


class ModuleBuilder(VenomBuilder):
    """A :class:`~vyper.venom.builder.VenomBuilder` that auto-prefixes all labels.

    Each ``ModuleBuilder`` owns one :class:`~vyper.venom.context.IRContext` and one
    entry :class:`~vyper.venom.function.IRFunction`.  All labels generated by this
    builder are namespaced under *prefix*, so multiple builders can be created
    independently and then merged into a single context via :meth:`merge` without
    label collisions.

    Args:
        prefix: Namespace prefix prepended to every generated label (e.g. ``"mod_a"``).
                When empty, behaviour is identical to plain :class:`VenomBuilder`.
        ctx:    Existing :class:`~vyper.venom.context.IRContext` to use.
                A fresh context is created when ``None``.
        fn:     Existing entry :class:`~vyper.venom.function.IRFunction` to use.
                A function named ``"<prefix>_main"`` is created when ``None``.
    """

    def __init__(
        self,
        prefix: str = "",
        ctx: IRContext | None = None,
        fn: IRFunction | None = None,
    ) -> None:
        if ctx is None:
            ctx = IRContext()
        if fn is None:
            fn_name = f"{prefix}_main" if prefix else "main"
            fn = ctx.create_function(fn_name)
        # The first (entry) function is designated as the context entry point
        # so that optimization passes (e.g. FunctionInlinerPass) can find it.
        if ctx.entry_function is None:
            ctx.entry_function = fn
        super().__init__(ctx, fn)
        self._prefix = prefix

    # ------------------------------------------------------------------
    # Label helpers
    # ------------------------------------------------------------------

    def named_label(self, name: str, is_symbol: bool = True) -> IRLabel:
        """Return a namespaced label ``<prefix>.<name>``.

        When *prefix* is empty the label value is just *name*.
        """
        value = f"{self._prefix}_{name}" if self._prefix else name
        return IRLabel(value, is_symbol=is_symbol)

    # ------------------------------------------------------------------
    # Overrides that inject the namespace prefix
    # ------------------------------------------------------------------

    def create_function(self, name: str) -> IRFunction:
        """Create a namespaced function in this builder's context.

        The function name is ``<prefix>.<name>`` (or just *name* when there is
        no prefix).  The builder's current emission block is **not** switched to
        the new function's entry — use :meth:`set_block` explicitly if needed.
        """
        full_name = self.named_label(name).value
        return self.ctx.create_function(full_name)

    def get_next_label(self, suffix: str = "") -> IRLabel:
        """Generate the next auto-label, prepending the namespace prefix."""
        label = self.ctx.get_next_label(suffix)
        if self._prefix:
            return IRLabel(f"{self._prefix}_{label.value}")
        return label

    def create_block(self, suffix: str = "") -> IRBasicBlock:
        """Create a new block with a namespace-prefixed auto-generated label.

        Overrides :meth:`~vyper.venom.builder.VenomBuilder.create_block` to use
        the prefixed :meth:`get_next_label` instead of
        :meth:`~vyper.venom.context.IRContext.get_next_label` directly, ensuring
        that all block labels are unique across merged modules.
        """
        label = self.get_next_label(suffix)
        return IRBasicBlock(label, self.fn)

    def set_block(self, bb: IRBasicBlock) -> None:
        """Switch the emission target to *bb* and update the active function.

        Overrides :meth:`~vyper.venom.builder.VenomBuilder.set_block` to also
        update :attr:`fn` to ``bb.parent``.  This ensures that
        :meth:`create_block` and :meth:`append_block` target the same function
        as the current block, which is required when building secondary functions
        via :meth:`create_function` + :meth:`set_block`.
        """
        self._current_bb = bb
        self.fn = bb.parent

    def append_data_section(self, name: str) -> None:
        """Append a namespaced data section to the context's data segment."""
        self.ctx.append_data_section(self.named_label(name))

    def append_data_item(self, data: IRLabel | bytes) -> None:
        """Append a data item to the most-recently opened data section."""
        self.ctx.append_data_item(data)

    # ------------------------------------------------------------------
    # Merge
    # ------------------------------------------------------------------

    def merge(self, *sources: IRContext) -> None:
        """Merge one or more :class:`~vyper.venom.context.IRContext` objects into
        this builder's context.

        Functions are cloned via :meth:`IRFunction.copy
        <vyper.venom.function.IRFunction.copy>` so reusable singleton sources
        (e.g. :data:`~pydefi.vm.stdlib.STDLIB`) stay intact across merges and
        downstream optimization passes never mutate them.

        Raises :class:`ValueError` on duplicate function, basic-block, or
        data-section labels *before* mutating ``self.ctx``.

        Args:
            *sources: Contexts to merge.  Their functions and data-segment
                      entries are cloned and appended to ``self.ctx``.
        """
        fn_labels = set(self.ctx.functions)
        bb_labels = {bb.label for bb in self.ctx.get_basic_blocks()}
        data_labels = {section.label for section in self.ctx.data_segment}

        for src in sources:
            for fn in src.functions.values():
                if fn.name in fn_labels:
                    raise ValueError(f"merge: duplicate function label {fn.name}")
                fn_labels.add(fn.name)
                for bb in fn.get_basic_blocks():
                    if bb.label in bb_labels:
                        raise ValueError(f"merge: duplicate basic block label {bb.label}")
                    bb_labels.add(bb.label)
            for section in src.data_segment:
                if section.label in data_labels:
                    raise ValueError(f"merge: duplicate data section label {section.label}")
                data_labels.add(section.label)

        for src in sources:
            for fn in src.functions.values():
                self.ctx.add_function(_clone_function(fn))
            self.ctx.data_segment.extend(DataSection(s.label, s.data_items.copy()) for s in src.data_segment)

    def compile(
        self,
        flags: VenomOptimizationFlags | None = None,
    ) -> bytes:
        """Compile this builder's context to EVM bytecode.

        Runs the full Venom IR optimization pipeline (via
        :func:`~vyper.venom.run_passes_on`) and then generates EVM bytecode.

        The :attr:`ctx` must have :attr:`~vyper.venom.context.IRContext.entry_function`
        set before calling this method.  The simplest way to satisfy that is to build
        the "main" entry-point logic directly on this builder — the constructor sets
        ``ctx.entry_function = fn`` automatically.

        Args:
            flags: Venom optimization flags.  Defaults to
                   :class:`~vyper.compiler.settings.VenomOptimizationFlags` (standard
                   O2 level).

        Returns:
            The compiled EVM bytecode as :class:`bytes`.
        """
        if flags is None:
            flags = VenomOptimizationFlags()
        run_passes_on(self.ctx, flags)
        compiler = VenomCompiler(self.ctx)
        asm = compiler.generate_evm_assembly(no_optimize=True)
        bytecode, _ = assembly_to_evm(asm)
        return bytecode
