"""Venom IR utilities for pydefi.

This module provides :class:`ModuleBuilder` — a :class:`~vyper.venom.builder.VenomBuilder`
subclass that auto-prefixes all generated labels under a namespace, enabling multiple
independently-generated code+data blocks to be merged into one :class:`~vyper.venom.context.IRContext`
without label collisions.

Calling convention for internal functions
-----------------------------------------

When building functions callable via ``invoke``, the last ``param()`` is always
the **return PC** (the address to jump back to after the function completes).
Correspondingly, ``ret()`` must receive the return values first and the return PC
**last**:

.. code-block:: python

    fn = mod.create_function("add")
    mod.set_block(fn.entry)
    x          = mod.param()          # first argument
    y          = mod.param()          # second argument
    return_pc  = mod.param()          # return-PC is always the last param
    result     = mod.add(x, y)
    mod.ret(result, return_pc)        # value(s), then return_pc

    # Caller side:
    rets = main.invoke(IRLabel("mod.add"), [IRLiteral(3), IRLiteral(4)], returns=1)

Data sections
-------------

Use :meth:`append_data_section` / :meth:`append_data_item` to attach constant
byte data.  To read it at runtime, combine :meth:`~vyper.venom.builder.VenomBuilder.offset`
with :meth:`~vyper.venom.builder.VenomBuilder.codecopy` — **do not** use
:meth:`~vyper.venom.builder.VenomBuilder.dload` (which adds ``code_end``, the total
bytecode length, instead of the code-section end):

.. code-block:: python

    mod.append_data_section("table")
    mod.append_data_item(b"\\x00" * 31 + b"\\x2a")   # literal 42

    src  = mod.offset(IRLiteral(0), mod.named_label("table"))
    buf  = mod.alloca(32)
    mod.codecopy(buf, src, IRLiteral(32))
    val  = mod.mload(buf)

Typical usage::

    from pydefi.vm.venom import ModuleBuilder
    from vyper.venom.basicblock import IRLabel, IRLiteral

    # Build module A
    mod_a = ModuleBuilder("mod_a")
    mod_a.append_data_section("table")               # DataSection(IRLabel("mod_a.table"))
    mod_a.append_data_item(b"\\x01\\x02\\x03\\x04")

    addr = mod_a.offset(IRLiteral(0), mod_a.named_label("table"))
    buf  = mod_a.alloca(32)
    mod_a.codecopy(buf, addr, IRLiteral(4))
    mod_a.stop()

    # Build module B — cross-module reference to A's table
    mod_b = ModuleBuilder("mod_b")
    addr_a = mod_b.offset(IRLiteral(0), IRLabel("mod_a.table"))
    buf2   = mod_b.alloca(32)
    mod_b.codecopy(buf2, addr_a, IRLiteral(4))
    mod_b.stop()

    # Merge everything and compile
    main = ModuleBuilder("main")
    main.merge(mod_a.ctx, mod_b.ctx)
    bytecode = main.compile()
"""

from __future__ import annotations

from vyper.compiler.settings import VenomOptimizationFlags
from vyper.evm.assembler.core import assembly_to_evm
from vyper.venom import VenomCompiler, run_passes_on
from vyper.venom.basicblock import IRBasicBlock, IRLabel
from vyper.venom.builder import VenomBuilder
from vyper.venom.context import IRContext
from vyper.venom.function import IRFunction

__all__ = ["ModuleBuilder"]


class ModuleBuilder(VenomBuilder):
    """A :class:`~vyper.venom.builder.VenomBuilder` that auto-prefixes all labels.

    Each ``ModuleBuilder`` owns one :class:`~vyper.venom.context.IRContext` and one
    entry :class:`~vyper.venom.function.IRFunction`.  All labels generated by this
    builder are namespaced under *prefix*, so multiple builders can be created
    independently and then merged into a single context via :meth:`merge` without
    label collisions.

    Args:
        prefix: Namespace prefix prepended to every generated label (e.g. ``"mod_a"``).
                When empty, behaviour is identical to plain :class:`VenomBuilder`.
        ctx:    Existing :class:`~vyper.venom.context.IRContext` to use.
                A fresh context is created when ``None``.
        fn:     Existing entry :class:`~vyper.venom.function.IRFunction` to use.
                A function named ``"<prefix>.main"`` is created when ``None``.
    """

    def __init__(
        self,
        prefix: str = "",
        ctx: IRContext | None = None,
        fn: IRFunction | None = None,
    ) -> None:
        if ctx is None:
            ctx = IRContext()
        if fn is None:
            fn_name = f"{prefix}.main" if prefix else "main"
            fn = ctx.create_function(fn_name)
        # The first (entry) function is designated as the context entry point
        # so that optimization passes (e.g. FunctionInlinerPass) can find it.
        if ctx.entry_function is None:
            ctx.entry_function = fn
        super().__init__(ctx, fn)
        self._prefix = prefix
        self._stdlib_merged: bool = False

    # ------------------------------------------------------------------
    # Label helpers
    # ------------------------------------------------------------------

    def named_label(self, name: str, is_symbol: bool = True) -> IRLabel:
        """Return a namespaced label ``<prefix>.<name>``.

        When *prefix* is empty the label value is just *name*.
        """
        value = f"{self._prefix}.{name}" if self._prefix else name
        return IRLabel(value, is_symbol=is_symbol)

    # ------------------------------------------------------------------
    # Overrides that inject the namespace prefix
    # ------------------------------------------------------------------

    def create_function(self, name: str) -> IRFunction:
        """Create a namespaced function in this builder's context.

        The function name is ``<prefix>.<name>`` (or just *name* when there is
        no prefix).  The builder's current emission block is **not** switched to
        the new function's entry — use :meth:`set_block` explicitly if needed.
        """
        full_name = self.named_label(name).value
        return self.ctx.create_function(full_name)

    def get_next_label(self, suffix: str = "") -> IRLabel:
        """Generate the next auto-label, prepending the namespace prefix."""
        label = self.ctx.get_next_label(suffix)
        if self._prefix:
            return IRLabel(f"{self._prefix}.{label.value}")
        return label

    def create_block(self, suffix: str = "") -> IRBasicBlock:
        """Create a new block with a namespace-prefixed auto-generated label.

        Overrides :meth:`~vyper.venom.builder.VenomBuilder.create_block` to use
        the prefixed :meth:`get_next_label` instead of
        :meth:`~vyper.venom.context.IRContext.get_next_label` directly, ensuring
        that all block labels are unique across merged modules.
        """
        label = self.get_next_label(suffix)
        return IRBasicBlock(label, self.fn)

    def set_block(self, bb: IRBasicBlock) -> None:
        """Switch the emission target to *bb* and update the active function.

        Overrides :meth:`~vyper.venom.builder.VenomBuilder.set_block` to also
        update :attr:`fn` to ``bb.parent``.  This ensures that
        :meth:`create_block` and :meth:`append_block` target the same function
        as the current block, which is required when building secondary functions
        via :meth:`create_function` + :meth:`set_block`.
        """
        self._current_bb = bb
        self.fn = bb.parent

    def append_data_section(self, name: str) -> None:
        """Append a namespaced data section to the context's data segment."""
        self.ctx.append_data_section(self.named_label(name))

    def append_data_item(self, data: IRLabel | bytes) -> None:
        """Append a data item to the most-recently opened data section."""
        self.ctx.append_data_item(data)

    # ------------------------------------------------------------------
    # Merge
    # ------------------------------------------------------------------

    def merge(self, *sources: IRContext) -> None:
        """Merge one or more :class:`~vyper.venom.context.IRContext` objects into
        this builder's context.

        All labels in *sources* are expected to already be namespace-prefixed (as
        produced by other :class:`ModuleBuilder` instances), so no collisions should
        occur.

        Args:
            *sources: Contexts to merge.  Their functions and data-segment entries
                      are appended to ``self.ctx``.
        """
        for src in sources:
            for fn in src.functions.values():
                self.ctx.add_function(fn)
            self.ctx.data_segment.extend(src.data_segment)

    # ------------------------------------------------------------------
    # Stdlib helpers
    # ------------------------------------------------------------------

    def _ensure_stdlib_merged(self) -> None:
        """Merge the stdlib context into this builder's context (at most once).

        Idempotent — subsequent calls after the first are no-ops.  Called
        automatically by :meth:`revert_if` and :meth:`assert_ge`.
        """
        if not self._stdlib_merged:
            from pydefi.vm.stdlib import STDLIB

            self.merge(STDLIB.ctx)
            self._stdlib_merged = True

    def revert_if(self, cond: object, msg: str) -> None:
        """Conditionally revert with ``Error(string)`` *msg*.

        Emits an ``invoke stdlib.revert_if`` instruction targeting the
        pre-built stdlib function.  The
        :class:`~vyper.venom.passes.function_inliner.FunctionInlinerPass`
        inlines it at the call site during :meth:`compile`.  The stdlib
        context is merged automatically if it hasn't been already.

        Args:
            cond: Venom IR operand — non-zero triggers the revert.
            msg:  Error message string (≤ 32 bytes UTF-8).

        Raises:
            ValueError: If *msg* encodes to more than 32 bytes.
        """
        from pydefi.vm.stdlib import revert_if as _revert_if

        _revert_if(self, cond, msg)

    def assert_ge(self, a: object, b: object, msg: str) -> None:
        """Assert *a* ≥ *b*, reverting with ``Error(string)`` *msg* if violated.

        Emits an ``invoke stdlib.assert_ge`` instruction targeting the
        pre-built stdlib function.  The
        :class:`~vyper.venom.passes.function_inliner.FunctionInlinerPass`
        inlines it at the call site during :meth:`compile`.  The stdlib
        context is merged automatically if it hasn't been already.

        Args:
            a:   Venom IR operand — left-hand side of the comparison.
            b:   Venom IR operand — right-hand side of the comparison.
            msg: Error message string (≤ 32 bytes UTF-8).

        Raises:
            ValueError: If *msg* encodes to more than 32 bytes.
        """
        from pydefi.vm.stdlib import assert_ge as _assert_ge

        _assert_ge(self, a, b, msg)

    def compile(
        self,
        flags: VenomOptimizationFlags | None = None,
        *,
        disable_mem_checks: bool = True,
    ) -> bytes:
        """Compile this builder's context to EVM bytecode.

        Runs the full Venom IR optimization pipeline (via
        :func:`~vyper.venom.run_passes_on`) and then generates EVM bytecode.

        The :attr:`ctx` must have :attr:`~vyper.venom.context.IRContext.entry_function`
        set before calling this method.  The simplest way to satisfy that is to build
        the "main" entry-point logic directly on this builder — the constructor sets
        ``ctx.entry_function = fn`` automatically.

        Args:
            flags: Venom optimization flags.  Defaults to
                   :class:`~vyper.compiler.settings.VenomOptimizationFlags` (standard
                   O2 level).
            disable_mem_checks: Pass ``True`` (the default) to skip the concrete
                                 memory-address check in
                                 :func:`~vyper.venom.run_passes_on`.  Required when
                                 using literal memory addresses such as ``PUSH0`` for
                                 ``return_`` offset.

        Returns:
            The compiled EVM bytecode as :class:`bytes`.
        """
        if flags is None:
            flags = VenomOptimizationFlags()
        run_passes_on(self.ctx, flags, disable_mem_checks=disable_mem_checks)
        compiler = VenomCompiler(self.ctx)
        asm = compiler.generate_evm_assembly(no_optimize=True)
        bytecode, _ = assembly_to_evm(asm)
        return bytecode
